model: null
optimizer:
  nfold: 5
pipelines:
  pipeline_cat_wrapper: null
  pipeline_homotopy: null
  pipeline_quantile: null
  pipeline_smallnans: null
  pipeline_tree: null
selector_first: null
selector_last: null
utilities: null
woe:
  random_state: 42
